package casino.cashier;


import casino.bet.BetID;
<<<<<<< HEAD
import casino.bet.MoneyAmount;
import casino.idfactory.IDFactory;

import javax.smartcardio.Card;
=======
import casino.idfactory.IDFactory;

import java.util.HashSet;
>>>>>>> 4902ac4408fe5d983c2107556504e354481a3b4d
import java.util.Set;

public class GamblerCard implements IGamblerCard {

<<<<<<< HEAD
    final private CardID id;
    private MoneyAmount balance;
    public GamblerCard()
    {
        this.id = (CardID) IDFactory.generateID("CardID");
        balance = new MoneyAmount(0);
    }

    /**
     * returns all generated betID's by this card
     *
     * @return a copied set of betID's generated by this card.
     */
    @Override
    public Set<BetID> returnBetIDs() {
        return null;
    }

    /**
     * returns all generated betID's by this card, and clears all betID's from the card.
     *
     * @return a copied set of betID's generated by this card.
     */
    @Override
    public Set<BetID> returnBetIDsAndClearCard() {
        return null;
    }

    /**
     * The card generates a unique betID for every bet made by the gambler on the machine.
     * A list of all generated betID’s is also stored on the card. BetID’s also contain a timestamp.
     *
     * @return
     */
    @Override
    public BetID generateNewBetID() {
        return null;
    }

    /**
     * return number of betID's generated on this card.
     *
     * @return
     */
    @Override
    public int getNumberOfBetIDs() {
        return 0;
=======
    private CardID cardID;
    private Set<BetID> betIDSet=new HashSet<BetID>();

    public GamblerCard(CardID cardID) {
        this.cardID=cardID;
    }

    @Override
    public Set<BetID> returnBetIDs() {
        return betIDSet;
    }

    @Override
    public Set<BetID> returnBetIDsAndClearCard() {
        Set<BetID> temp=returnBetIDs();
        betIDSet.clear();
        return temp;
    }

    @Override
    public BetID generateNewBetID() {
        BetID newBeltID= (BetID) IDFactory.generateID("BeltID");
        betIDSet.add(newBeltID);
        return newBeltID;
    }

    @Override
    public int getNumberOfBetIDs() {
        return betIDSet.size();
>>>>>>> 4902ac4408fe5d983c2107556504e354481a3b4d
    }

    @Override
    public CardID getCardID() {
<<<<<<< HEAD
        return id;
    }

    @Override
    public void setBalance(MoneyAmount amount)
    {
        balance = amount;
    }

    @Override
    public MoneyAmount getBalance() {
        return balance;
=======
        return cardID;
>>>>>>> 4902ac4408fe5d983c2107556504e354481a3b4d
    }
}
