package casino.cashier;


import casino.bet.BetID;
import casino.bet.MoneyAmount;
import casino.idfactory.IDFactory;
import javax.smartcardio.Card;
import java.util.HashSet;
import java.util.Set;

public class GamblerCard implements IGamblerCard {

    final private CardID id;
    private MoneyAmount balance;
    private Set<BetID> betIDSet=new HashSet<BetID>();

    public GamblerCard()
    {
        this.id = (CardID) IDFactory.generateID("IDCard");
        balance = new MoneyAmount(0);
    }

    public GamblerCard(CardID id) {
        this.id = id;
    }

    /**
     * returns all generated betID's by this card
     *
     * @return a copied set of betID's generated by this card.
     */
    @Override
    public Set<BetID> returnBetIDs() {
        return betIDSet;
    }

    /**
     * returns all generated betID's by this card, and clears all betID's from the card.
     *
     * @return a copied set of betID's generated by this card.
     */
    @Override
    public Set<BetID> returnBetIDsAndClearCard() {
        Set<BetID> temp=returnBetIDs();
        betIDSet.clear();
        return temp;
    }

    /**
     * The card generates a unique betID for every bet made by the gambler on the machine.
     * A list of all generated betID’s is also stored on the card. BetID’s also contain a timestamp.
     *
     * @return
     */
    @Override
    public BetID generateNewBetID() {
        BetID newBeltID= (BetID) IDFactory.generateID("BeltID");
        betIDSet.add(newBeltID);
        return newBeltID;
    }

    /**
     * return number of betID's generated on this card.
     *
     * @return
     */
    @Override
    public int getNumberOfBetIDs() {
        return betIDSet.size();
    }

    @Override
    public CardID getCardID() {
        return id;
    }

    @Override
    public void setBalance(MoneyAmount amount)
    {
        balance = amount;
    }

    @Override
    public MoneyAmount getBalance() {
        return balance;
    }
}
